# Generated by Django 5.0.2 on 2024-04-12 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0002_slides_delete_presentacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slides',
        ),
    ]
